### ISSUE TITLE
Hello！

### ISSUE THREAD

**Issue by tjwtjw666** [mkirchler/transferGWAS#2]
Dear all,
  
Your creation is excellent. It's going wrong when I running the following command :conda env create --file C:/Users/86188/Desktop/environment_cpu.yml.Conda displayed that :conda env create --file C:/Users/86188/Desktop/environment_cpu.yml.This confuses me.
 
Do you know how to solve the above problems?
  
Thanks in advance!

Best regards
T

  
![60f9c2b186974866538c9c084d7c8f2](https://github.com/mkirchler/transferGWAS/assets/150512358/f0c4d123-1669-47fb-9b63-2edf47f8820e)
![Uploading 34d86aa07e00be621880e60d45fe540.png…]()

**Comment by mkirchler** [comment]
Hi, thanks for your interest. Python 3.6 has reached end of life, and I'm also not entirely sure about specific differences on Windows machines (all work here was tested only on linux machines).
However, almost everything should work pretty much the same, even if your system doesn't support exactly the same packages. In your case, I'd recommend just manually installing the most important packages that couldn't be found here  (e.g., `conda install scikit-learn=0.23`, and similarly for scipy, numpy, pandas; all the others listed in your screenshot should probably be installed automatically). Also consider using a newer version of python :) 
I'll close this issue, but feel free to re-open, if you still have problems

**Comment by tjwtjw666** [comment]
Thanks for your help!I have solved the problem.
